name: JVM Environment Execution
run-name: ${{ github.actor }} is beeing tested.
on: [push]
jobs:
  Build-Run-JVM-Machine:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Set up LLVM
        run: sudo apt install llvm

      - name: Compiling JVM project
        run: |
          cd ${{ github.workspace }}
          make

      - name: Testing JVM Project
        run: |
          cd ${{ github.workspace }}
          make test

      - name: Set up CPP Check
        run: sudo apt install cppcheck -y

      - name: Running Address Sanitizer
        run: make asan

      - name: Running Undefined Behavior Sanitizer
        run: make ubsan

      - name: Running CPP Check
        run: |
          cd ${{ github.workspace }}
          make cppcheck
